version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${KAFKA_HOST}:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  backend:
    build: .
    depends_on:
      - kafka
      - db
    volumes:
      - ./assets:/assets
    ports:
      - "5000:3000"
    environment:
      KAFKA_URL: kafka:29092
      DB_HOST: db
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - 3088:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1
  db:
    image: mysql:8.0.25
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '1'
      LANG: C.UTF-8
    volumes:
      - ./docker/.docker/data/db:/var/lib/mysql
      - ./docker/.docker/mnt:/mnt
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

